[colors]
Root = "#14131E"
Surface0 = "#1F1D2D"
Surface1 = "#242336"
Surface2 = "#353553"
Surface3 = "#494764"
Surface4 = "#555275"
Foreground0 = "#C8D5F1"
Foreground1 = "#949BB9"
Foreground2 = "#747A9C"
BlueFgDim = "#8CAAD1"
BlueFg = "#9ABFE8"
PurpleFgDim = "#9D97D3"
PurpleFg = "#B0A8EB"
PinkFgDim = "#C091D0"
PinkFg = "#D9A1E8"
OrangeFgDim = "#CF9876"
OrangeFg = "#EBB17B"
GreenFgDim = "#B3C48D"
GreenFg = "#C9DE96"
RedFgDim = "#CA5072"
RedFg = "#E55376"
YellowFgDim = "#CDBB91"
YellowFg = "#E9D39C"
